[package]
name = "luhnr"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
csv = "1.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "luhn_benchmark"
harness = false
